import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins", // matches your CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <div className="max-w-[960px] my-0 mx-auto py-[2rem] px-[1rem] text-center sm:px-[0.5rem] sm:py-[1rem]">
          {children}
          {/* footer  */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
